name = "ContextTemplatesCustom"
uid = "b6765b414-63334-4352-b81c-7e0e2d4bccdab"
version = 4
description = "Adds context templates on the ground for t2/t3 pd grid, t2/t3 AA grids fixed icon Template now works when hovering over t2pd/t3 sams"
author = "lordfappington"
icon = "/mods/ContextTemplatesCustom/icon.png"
exclusive = false
ui_only = true
conflicts = {}
