name = "ContextGroundTemplates"
uid = "b999b414-6734-4352-b81c-7e0e2d4bccda"
version = 1
description = "Provides late-game cap/append context templates such as: Gateway with T2 Fabs, T3 Pgen with T2 Fabs"
author = "lordfappington"
icon = "icon.png"
exclusive = false
ui_only = true
conflicts = {}
