---@type ContextBasedTemplate
Template = {
    Name = 'Capped Defense',
    TriggersOnMassDeposit = true,
    TemplateSortingOrder = 104,
    templateData = {
        10,
        10,
        {
            'ueb2108',
            14356,
            0,
            0
        },
        {
            'ueb4202',
            14510,
            -6,
            -6
        },
        {
            'ueb4201',
            14625,
            -2,
            -8
        },
        {
            'ueb2204',
            14719,
            -8,
            -2
        }
    },
 }